version: '3'

# Hono + Datastar on Cloudflare Workers
#
# Prerequisites:
#   - task (https://taskfile.dev) — the ONLY prerequisite
#   - Bun is auto-installed by `task deps` if not present
#
# Quick start:
#   task deps        # install Bun (if needed) + all dependencies
#   task dev         # start dev server with live logs
#   task test        # run e2e tests against local server
#   task deploy      # deploy to Cloudflare Workers
#
# All tasks are idempotent — safe to run multiple times.
#
# Architecture notes:
#   - Counter state stored in D1 (Cloudflare's SQLite) for durability
#   - Atomic increment/decrement via UPDATE ... RETURNING
#   - Local dev uses miniflare's built-in local SQLite (automatic)
#   - Static files served via [assets] in wrangler.toml (NOT [site])

# Ensure ~/.bun/bin is on PATH so freshly-installed Bun is found immediately
env:
  PATH:
    sh: echo "$HOME/.bun/bin:$PATH"

vars:
  LOG_FILE: .wrangler/wrangler.log
  LOCAL_URL: http://localhost:8787
  # Set this to your deployed worker URL (printed by `task deploy`)
  DEPLOYED_URL: '{{.DEPLOYED_URL | default "https://test-hono.gedw99.workers.dev"}}'

tasks:
  default:
    desc: "Lists all available tasks"
    cmds:
      - task --list-all
    silent: true

  # --- Development ---

  dev:
    desc: "Starts the dev server with live logs"
    cmds:
      - task: stop
      - task: start
      - task: logs

  start:
    desc: "Starts the server in the background (skips if already running)"
    cmds:
      - |
        if curl -s -o /dev/null -w '' {{.LOCAL_URL}}/ 2>/dev/null; then
          echo "Server already running at {{.LOCAL_URL}}"
          exit 0
        fi
        mkdir -p .wrangler
        bunx wrangler d1 migrations apply test-hono-db --local
        bun run dev > {{.LOG_FILE}} 2>&1 &
        for i in $(seq 1 15); do
          curl -s -o /dev/null -w '' {{.LOCAL_URL}}/ 2>/dev/null && break
          sleep 1
        done
        echo "Server ready at {{.LOCAL_URL}}"
    silent: true

  stop:
    desc: "Stops the development server (no-op if not running)"
    cmds:
      - pkill -f "wrangler dev" || true
    silent: true

  restart:
    desc: "Stops and starts the development server"
    cmds:
      - task: stop
      - sleep 1
      - |
        mkdir -p .wrangler
        bunx wrangler d1 migrations apply test-hono-db --local
        bun run dev > {{.LOG_FILE}} 2>&1 &
        for i in $(seq 1 15); do
          curl -s -o /dev/null -w '' {{.LOCAL_URL}}/ 2>/dev/null && break
          sleep 1
        done
        echo "Server ready at {{.LOCAL_URL}}"
    silent: true

  logs:
    desc: "Follow the development server logs"
    cmds:
      - tail -f {{.LOG_FILE}}

  # --- Testing ---

  test:
    desc: "Runs Playwright e2e tests against local dev server"
    cmds:
      - task: start
      - bun run test

  test:deployed:
    desc: "Runs e2e tests against the deployed worker ({{.DEPLOYED_URL}})"
    summary: |
      Usage:
        task test:deployed                              # uses DEPLOYED_URL from Taskfile
        task test:deployed -- https://your.workers.dev  # override with explicit URL
        DEPLOYED_URL=https://... task test:deployed      # override via env var
    cmds:
      - echo "Testing against {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.DEPLOYED_URL}}{{end}}"
      - BASE_URL={{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.DEPLOYED_URL}}{{end}} bun run test

  # --- Deployment ---

  login:
    desc: "Authenticates with Cloudflare (skips if already logged in)"
    cmds:
      - |
        if bunx wrangler whoami &>/dev/null; then
          echo "Already authenticated with Cloudflare"
          bunx wrangler whoami
          exit 0
        fi
        bunx wrangler login
    silent: true

  deploy:
    desc: "Deploys the worker to Cloudflare (runs remote migrations first)"
    cmds:
      - bunx wrangler d1 migrations apply test-hono-db --remote
      - bun run deploy

  ci:secrets:
    desc: "Creates Cloudflare API token (browser) and sets GitHub secrets"
    summary: |
      Automates the full CI setup:
        1. Gets account ID from your local wrangler login
        2. Opens a browser to create an API token (automated via Playwright)
        3. Sets both as GitHub secrets via gh CLI

      Usage:
        task ci:secrets                    # fully automated (opens browser)
        task ci:secrets -- YOUR_API_TOKEN  # skip browser, use existing token
    cmds:
      - |
        # Ensure logged in to Cloudflare
        ACCOUNT_ID=$(bunx wrangler whoami 2>/dev/null | grep -oE '[a-f0-9]{32}' | head -1)
        if [ -z "$ACCOUNT_ID" ]; then
          echo "Not logged in to Cloudflare. Run 'task login' first."
          exit 1
        fi
        echo "Account ID: $ACCOUNT_ID"

        # Get API token: from CLI args, or create via Playwright
        API_TOKEN="{{.CLI_ARGS}}"
        if [ -z "$API_TOKEN" ]; then
          echo ""
          echo "Opening browser to create API token..."
          API_TOKEN=$(bun scripts/create-cf-token.ts 2>/dev/tty) || true
        fi

        # Fallback: prompt user to paste
        if [ -z "$API_TOKEN" ]; then
          echo ""
          printf "Paste your API token (or Ctrl+C to abort): "
          read -r API_TOKEN
        fi

        if [ -z "$API_TOKEN" ]; then
          echo "No API token provided."
          exit 1
        fi

        # Set GitHub secrets
        echo "$ACCOUNT_ID" | gh secret set CLOUDFLARE_ACCOUNT_ID
        echo "$API_TOKEN" | gh secret set CLOUDFLARE_API_TOKEN
        echo ""
        echo "GitHub secrets set:"
        echo "  CLOUDFLARE_ACCOUNT_ID = $ACCOUNT_ID"
        echo "  CLOUDFLARE_API_TOKEN  = (hidden)"
        echo ""
        echo "CI will now auto-deploy on push to main."
    silent: true

  # --- Database ---

  db:create:
    desc: "Creates the D1 database on Cloudflare (one-time setup)"
    cmds:
      - bunx wrangler d1 create test-hono-db
    silent: true

  db:migrate:
    desc: "Applies D1 migrations locally"
    cmds:
      - bunx wrangler d1 migrations apply test-hono-db --local
    silent: true

  db:migrate:remote:
    desc: "Applies D1 migrations to the remote database"
    cmds:
      - bunx wrangler d1 migrations apply test-hono-db --remote
    silent: true

  # --- Setup ---

  bun:install:
    desc: "Installs Bun if not already present"
    cmds:
      - |
        if command -v bun &>/dev/null; then
          echo "Bun $(bun --version) already installed"
          exit 0
        fi
        echo "Installing Bun..."
        curl -fsSL https://bun.sh/install | bash
        echo "Bun installed to ~/.bun/bin/bun"
    silent: true

  deps:
    desc: "Installs Bun (if needed) and all dependencies"
    cmds:
      - task: bun:install
      - |
        export PATH="$HOME/.bun/bin:$PATH"
        bun install
        bunx playwright install --with-deps chromium
